### ISSUE TITLE
Theme doesn't load

### ISSUE THREAD

**Issue by im-coder-lg** [TimerX-App/TimerX#64] opened 2022-01-24 05:57 UTC
### Discussed in https://github.com/TimerX-App/TimerX/discussions/63

<div type='discussions-op-text'>

<sup>Originally posted by **not-nef**, January 24, 2022</sup>
Yesterday i tried to compile timerx on my pc. It was horrible. The theme didnt load, and the blurring didnt work. If the github actions builds also look like that, we cant release tomorrow</div>

We must fix this before the Republic Day release.

**Comment by im-coder-lg** [comment] 2022-01-24 06:05
@sumeshir26 can you please check if the same applies to you? And if you have a fix, can you commit it?

**Comment by sumeshir26** [comment] 2022-01-24 06:22
@im-coder-lg I am facing the same issue. I might know a fix...

**Comment by sumeshir26** [comment] 2022-01-24 06:54
Based on the window, it is the same problem you had in the Blur PR. How did you fix it?

**Comment by im-coder-lg** [comment] 2022-01-24 06:56
Who? Me? It was the theme! It works like this: Config is saved. If it's system, it mimics Windows 7, if it's Light or Dark, it uses Blur there. Afaik, dark mode's blur worked better.

**Comment by not-nef** [comment] 2022-01-24 17:59
> Based on the window, it is the same problem you had in the Blur PR. How did you fix it?

It was fixed in the source code. This has to be an issue with cx_freeze because when starting the app from source it works fine.

**Comment by not-nef** [comment] 2022-01-24 18:19
![image](https://user-images.githubusercontent.com/83908932/150841002-185700cc-c208-4ada-8d90-b189a8b1065f.png)

I think the highlighted line causes the build to cancel. Does anyone know what it means? @TimerX-App/reviewers

**Comment by im-coder-lg** [comment] 2022-01-25 02:02
Hmm... I will test this soon.

**Comment by sumeshir26** [comment] 2022-01-25 03:11
@not-nef I get this error:
![image](https://user-images.githubusercontent.com/68823982/150904026-5e36b26c-c0d4-4a64-b2c7-01ae1aa2829d.png)

**Comment by sumeshir26** [comment] 2022-01-25 04:21
@im-coder-lg How did you fix this: https://github.com/TimerX-App/TimerX/pull/46#issuecomment-1015155905?

**Comment by im-coder-lg** [comment] 2022-01-25 04:34
Just switched the theme.

**Comment by im-coder-lg** [comment] 2022-01-25 04:44
And also restarted the app.

**Comment by im-coder-lg** [comment] 2022-01-25 04:55
I think it's related to the Blur PR. This happens due to DarkDetect. If you set it to System, it will use basic Tk UI with transparency. If you put light or dark mode, it will NOT apply blur and stick with transparency. I think it's due to the `-transparency` tag in the code.

**Comment by sumeshir26** [comment] 2022-01-25 05:15
@im-coder-lg Yes, now that I set the default theme in `utils.py` as Light, the issue is fixed. The System option is messed up. We could completely disable the `System` option until we find a fix.

**Comment by not-nef** [comment] 2022-01-25 05:40
When is republic day?

**Comment by not-nef** [comment] 2022-01-25 05:42
> @im-coder-lg Yes, now that I set the default theme in `utils.py` as Light, the issue is fixed. The System option is messed up. We could completely disable the `System` option until we find a fix.

I will do that after school

**Comment by not-nef** [comment] 2022-01-25 05:43
> I think it's related to the Blur PR. This happens due to DarkDetect. If you set it to System, it will use basic Tk UI with transparency. If you put light or dark mode, it will NOT apply blur and stick with transparency. I think it's due to the `-transparency` tag in the code.

That seems to happen, but i see no explanation to that. This must be a bug

**Comment by im-coder-lg** [comment] 2022-01-25 05:49
> When is republic day?

26 Jan in India. Wikipedia will tell you more about the specialty. Also, I think we shouldn't use Darkdetect, that was the thing that made the problem. It mimicked Windows 7.

**Comment by not-nef** [comment] 2022-01-25 05:55
> > When is republic day?
> 
> 
> 
> 26 Jan in India. Wikipedia will tell you more about the specialty. Also, I think we shouldn't use Darkdetect, that was the thing that made the problem. It mimicked Windows 7.

I could make it exclusive for windows 10 and 11

**Comment by im-coder-lg** [comment] 2022-01-25 06:00
> I could make it exclusive for windows 10 and 11

Try that now.

**Closed** 2022-01-26 05:10 UTC
Labels: bug, help wanted, high priority
